# Generated by Django 5.2.5 on 2025-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_system_logs_remove_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
