# Generated by Django 5.2.5 on 2025-08-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_folders_folder_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='file_quantity',
        ),
    ]
