# Generated by Django 5.2.5 on 2025-08-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_folders_file_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder_files',
            old_name='file_name',
            new_name='file',
        ),
    ]
