# Generated by Django 5.2.5 on 2025-08-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_file_name_folder_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder_files',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
