# Generated by Django 5.2.5 on 2025-08-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_folder_files_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder_files',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder_files',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
    ]
