# Generated by Django 5.2.5 on 2025-08-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_folder_files_is_archive_folder_files_is_confidential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder_files',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.folders'),
        ),
    ]
