# Generated by Django 5.2.5 on 2025-08-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_folder_files_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info1', models.TextField(blank=True, null=True)),
                ('info2', models.TextField(blank=True, null=True)),
                ('info3', models.TextField(blank=True, null=True)),
                ('info4', models.TextField(blank=True, null=True)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
