# Generated by Django 5.2.5 on 2025-08-24 23:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_logs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss', models.TextField()),
                ('gsis', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_no', models.TextField(blank=True, null=True)),
                ('fixed_rate', models.TextField(blank=True, null=True)),
                ('salary_adjustment', models.TextField(blank=True, null=True)),
                ('salary_after_adjustment', models.TextField(blank=True, null=True)),
                ('overtime_pay', models.TextField(blank=True, null=True)),
                ('total_salary_overtime', models.TextField(blank=True, null=True)),
                ('absent', models.TextField(blank=True, null=True)),
                ('late', models.TextField(blank=True, null=True)),
                ('deductions', models.TextField(blank=True, null=True)),
                ('total_amount_due', models.TextField(blank=True, null=True)),
                ('check_no', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gross_compensation', models.TextField(blank=True, null=True)),
                ('date_prepared', models.DateField(blank=True, null=True)),
                ('date_release', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.FileField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payroll')),
            ],
        ),
        migrations.RemoveField(
            model_name='folder_files',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder_files',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='folders',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='System_logs',
        ),
        migrations.DeleteModel(
            name='Folder_Files',
        ),
        migrations.DeleteModel(
            name='Folders',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
