# Generated by Django 5.2.5 on 2025-08-25 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_governmentshares_payroll_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.TextField(default='Pending'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
