# Generated by Django 5.2.5 on 2025-10-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payroll_status_alter_qrcode_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentshares',
            name='staff',
        ),
        migrations.AddField(
            model_name='governmentshares',
            name='payroll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.payroll'),
            preserve_default=False,
        ),
    ]
