# Generated by Django 5.2.7 on 2025-10-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_governmentshares_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_status', models.TextField(default='Pending')),
                ('hr_reason', models.TextField()),
                ('budget_status', models.TextField(default='Pending')),
                ('budget_reason', models.TextField()),
                ('president_status', models.TextField(default='Pending')),
                ('president_reason', models.TextField()),
                ('cashier_status', models.TextField(default='Pending')),
                ('cashier_reason', models.TextField()),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payroll')),
            ],
        ),
    ]
