# Generated by Django 5.2.7 on 2025-10-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_payrollstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollstatus',
            name='budget_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='budget_status',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='cashier_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='cashier_status',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='hr_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='hr_status',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='president_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='president_status',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
