# Generated by Django 5.2.7 on 2025-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_payrollstatus_budget_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollstatus',
            name='budget_date_updated',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollstatus',
            name='cashier_date_updated',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollstatus',
            name='hr_date_updated',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollstatus',
            name='president_date_updated',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
