# Generated by Django 5.2.7 on 2025-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_payrollstatus_budget_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollstatus',
            name='budget_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='cashier_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='hr_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollstatus',
            name='president_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
