# Generated by Django 5.2.7 on 2025-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_payrollstatus_budget_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='absent',
            new_name='bir',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='check_no',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='fixed_rate',
            new_name='ffasa',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='gross_compensation',
            new_name='gsis_consolidated_loan',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='late',
            new_name='gsis_educ',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='overtime_pay',
            new_name='gsis_emergency',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='payroll_no',
            new_name='gsis_mpl',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='remarks',
            new_name='gsis_personal_share',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='salary_adjustment',
            new_name='hdmf_mpl',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='salary_after_adjustment',
            new_name='hdmf_personal_share',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='total_amount_due',
            new_name='hdmf_salary_load',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='total_salary_overtime',
            new_name='net_monthly_income',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='date_prepared',
        ),
        migrations.AddField(
            model_name='payroll',
            name='ldaap_ada_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='phic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='valley_bank_load',
            field=models.TextField(blank=True, null=True),
        ),
    ]
