# Generated by Django 5.2.7 on 2025-11-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_absent_payroll_bir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='monthly_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pera_aca',
            field=models.TextField(blank=True, null=True),
        ),
    ]
