# Generated by Django 5.2.7 on 2025-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_payroll_monthly_income_payroll_pera_aca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date_release',
            field=models.TextField(blank=True, null=True),
        ),
    ]
